// Auth action types
export const AUTH_RESET = 'AUTH_RESET';
export const AUTH_ERROR_RESET = 'AUTH_ERROR_RESET';

export const AUTH_PAGE_ON = 'AUTH_PAGE_ON';
export const AUTH_PAGE_OFF = 'AUTH_PAGE_OFF';

export const USER_PAGE_ON = 'USER_PAGE_ON';
export const USER_PAGE_OFF = 'USER_PAGE_OFF';

export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const POST_PROFILE_START = 'POST_PROFILE_START';
export const POST_PROFILE_SUCCESS = 'POST_PROFILE_SUCCESS';
export const POST_PROFILE_FAIL = 'POST_PROFILE_FAIL';

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const JOIN_COMMUNITY_START = 'JOIN_COMMUNITY_START';
export const JOIN_COMMUNITY_SUCCESS = 'JOIN_COMMUNITY_SUCCESS';
export const JOIN_COMMUNITY_FAIL = 'JOIN_COMMUNITY_FAIL';

export const QUIT_COMMUNITY_START = 'QUIT_COMMUNITY_START';
export const QUIT_COMMUNITY_SUCCESS = 'QUIT_COMMUNITY_SUCCESS';
export const QUIT_COMMUNITY_FAIL = 'QUIT_COMMUNITY_FAIL';

export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';




// Csrf action types
export const CSRF_RESET = 'CSRF_RESET';
export const CSRF_ERROR_RESET = 'CSRF_ERROR_RESET';

export const CSRF_TOKEN_START = 'CSRF_TOKEN_START';
export const CSRF_TOKEN_SUCCESS = 'CSRF_TOKEN_SUCCESS';
export const CSRF_TOKEN_FAIL = 'CSRF_TOKEN_FAIL';





// Shop action types
export const SHOP_RESET = 'SHOP_RESET';
export const SHOP_ERROR_RESET = 'SHOP_ERROR_RESET';

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCT_START = 'GET_PRODUCT_START';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const GET_CART_START = 'GET_CART_START';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';

export const ADD_CART_ITEM_START = 'ADD_CART_ITEM_START';
export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS';
export const ADD_CART_ITEM_FAIL = 'ADD_CART_ITEM_FAIL';

export const SUBTRACT_CART_ITEM_START = 'SUBTRACT_CART_ITEM_START';
export const SUBTRACT_CART_ITEM_SUCCESS = 'SUBTRACT_CART_ITEM_SUCCESS';
export const SUBTRACT_CART_ITEM_FAIL = 'SUBTRACT_CART_ITEM_FAIL';

export const DELETE_CART_ITEM_START = 'DELETE_CART_ITEM_START';
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS';
export const DELETE_CART_ITEM_FAIL = 'DELETE_CART_ITEM_FAIL';

export const CLEAR_CART_START = 'CLEAR_CART_START';
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';
export const CLEAR_CART_FAIL = 'CLEAR_CART_FAIL';

export const GET_MY_COMMUNITY_START = 'GET_MY_COMMUNITY_START';
export const GET_MY_COMMUNITY_SUCCESS = 'GET_MY_COMMUNITY_SUCCESS';
export const GET_MY_COMMUNITY_FAIL = 'GET_MY_COMMUNITY_FAIL';

export const GET_MY_COMMUNITIES_START = 'GET_MY_COMMUNITIES_START';
export const GET_MY_COMMUNITIES_SUCCESS = 'GET_MY_COMMUNITIES_SUCCESS';
export const GET_MY_COMMUNITIES_FAIL = 'GET_MY_COMMUNITIES_FAIL';

export const POST_MY_COMMUNITY_START = 'POST_MY_COMMUNITY_START';
export const POST_MY_COMMUNITY_SUCCESS = 'POST_MY_COMMUNITY_SUCCESS';
export const POST_MY_COMMUNITY_FAIL = 'POST_MY_COMMUNITY_FAIL';

export const GET_COMMUNITY_START = 'GET_COMMUNITY_START';
export const GET_COMMUNITY_SUCCESS = 'GET_COMMUNITY_SUCCESS';
export const GET_COMMUNITY_FAIL = 'GET_COMMUNITY_FAIL';

export const GET_COMMUNITIES_START = 'GET_COMMUNITIES_START';
export const GET_COMMUNITIES_SUCCESS = 'GET_COMMUNITIES_SUCCESS';
export const GET_COMMUNITIES_FAIL = 'GET_COMMUNITIES_FAIL';

export const GET_CHECKOUT_START = 'GET_CHECKOUT_START';
export const GET_CHECKOUT_SUCCESS = 'GET_CHECKOUT_SUCCESS';
export const GET_CHECKOUT_FAIL = 'GET_CHECKOUT_FAIL';

export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const POST_ORDER_START = 'POST_ORDER_START';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL';

export const GET_INVOICE_START = 'GET_INVOICE_START';
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_FAIL = 'GET_INVOICE_FAIL';




// Admin action types
export const ADMIN_RESET = 'ADMIN_RESET';
export const ADMIN_ERROR_RESET = 'ADMIN_ERROR_RESET';

export const ADMIN_GET_USERS_START = 'ADMIN_GET_USERS_START';
export const ADMIN_GET_USERS_SUCCESS = 'ADMIN_GET_USERS_SUCCESS';
export const ADMIN_GET_USERS_FAIL = 'ADMIN_GET_USERS_FAIL';

export const ADMIN_STORE_USER_START = 'ADMIN_STORE_USER_START';
export const ADMIN_STORE_USER_SUCCESS = 'ADMIN_STORE_USER_SUCCESS';
export const ADMIN_STORE_USER_FAIL = 'ADMIN_STORE_USER_FAIL';

export const ADMIN_CREATE_USER_START = 'ADMIN_CREATE_USER_START';
export const ADMIN_CREATE_USER_SUCCESS = 'ADMIN_CREATE_USER_SUCCESS';
export const ADMIN_CREATE_USER_FAIL = 'ADMIN_CREATE_USER_FAIL';

export const ADMIN_EDIT_USER_START = 'ADMIN_EDIT_USER_START';
export const ADMIN_EDIT_USER_SUCCESS = 'ADMIN_EDIT_USER_SUCCESS';
export const ADMIN_EDIT_USER_FAIL = 'ADMIN_EDIT_USER_FAIL';

export const ADMIN_UPDATE_USER_START = 'ADMIN_UPDATE_USER_START';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAIL = 'ADMIN_UPDATE_USER_FAIL';

export const ADMIN_DESTROY_USER_START = 'ADMIN_DESTROY_USER_START';
export const ADMIN_DESTROY_USER_SUCCESS = 'ADMIN_DESTROY_USER_SUCCESS';
export const ADMIN_DESTROY_USER_FAIL = 'ADMIN_DESTROY_USER_FAIL';



export const ADMIN_GET_ORDERS_START = 'ADMIN_GET_ORDERS_START';
export const ADMIN_GET_ORDERS_SUCCESS = 'ADMIN_GET_ORDERS_SUCCESS';
export const ADMIN_GET_ORDERS_FAIL = 'ADMIN_GET_ORDERS_FAIL';

export const ADMIN_DESTROY_ORDER_START = 'ADMIN_DESTROY_ORDER_START';
export const ADMIN_DESTROY_ORDER_SUCCESS = 'ADMIN_DESTROY_ORDER_SUCCESS';
export const ADMIN_DESTROY_ORDER_FAIL = 'ADMIN_DESTROY_ORDER_FAIL';



export const ADMIN_GET_PRODUCTS_START = 'ADMIN_GET_PRODUCTS_START';
export const ADMIN_GET_PRODUCTS_SUCCESS = 'ADMIN_GET_PRODUCTS_SUCCESS';
export const ADMIN_GET_PRODUCTS_FAIL = 'ADMIN_GET_PRODUCTS_FAIL';

export const ADMIN_STORE_PRODUCT_START = 'ADMIN_STORE_PRODUCT_START';
export const ADMIN_STORE_PRODUCT_SUCCESS = 'ADMIN_STORE_PRODUCT_SUCCESS';
export const ADMIN_STORE_PRODUCT_FAIL = 'ADMIN_STORE_PRODUCT_FAIL';

export const ADMIN_EDIT_PRODUCT_START = 'ADMIN_EDIT_PRODUCT_START';
export const ADMIN_EDIT_PRODUCT_SUCCESS = 'ADMIN_EDIT_PRODUCT_SUCCESS';
export const ADMIN_EDIT_PRODUCT_FAIL = 'ADMIN_EDIT_PRODUCT_FAIL';

export const ADMIN_UPDATE_PRODUCT_START = 'ADMIN_UPDATE_PRODUCT_START';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAIL = 'ADMIN_UPDATE_PRODUCT_FAIL';

export const ADMIN_DESTROY_PRODUCT_START = 'ADMIN_DESTROY_PRODUCT_START';
export const ADMIN_DESTROY_PRODUCT_SUCCESS = 'ADMIN_DESTROY_PRODUCT_SUCCESS';
export const ADMIN_DESTROY_PRODUCT_FAIL = 'ADMIN_DESTROY_PRODUCT_FAIL';



export const ADMIN_GET_ROLES_START = 'ADMIN_GET_ROLES_START';
export const ADMIN_GET_ROLES_SUCCESS = 'ADMIN_GET_ROLES_SUCCESS';
export const ADMIN_GET_ROLES_FAIL = 'ADMIN_GET_ROLES_FAIL';

export const ADMIN_STORE_ROLE_START = 'ADMIN_STORE_ROLE_START';
export const ADMIN_STORE_ROLE_SUCCESS = 'ADMIN_STORE_ROLE_SUCCESS';
export const ADMIN_STORE_ROLE_FAIL = 'ADMIN_STORE_ROLE_FAIL';

export const ADMIN_EDIT_ROLE_START = 'ADMIN_EDIT_ROLE_START';
export const ADMIN_EDIT_ROLE_SUCCESS = 'ADMIN_EDIT_ROLE_SUCCESS';
export const ADMIN_EDIT_ROLE_FAIL = 'ADMIN_EDIT_ROLE_FAIL';

export const ADMIN_UPDATE_ROLE_START = 'ADMIN_UPDATE_ROLE_START';
export const ADMIN_UPDATE_ROLE_SUCCESS = 'ADMIN_UPDATE_ROLE_SUCCESS';
export const ADMIN_UPDATE_ROLE_FAIL = 'ADMIN_UPDATE_ROLE_FAIL';

export const ADMIN_DESTROY_ROLE_START = 'ADMIN_DESTROY_ROLE_START';
export const ADMIN_DESTROY_ROLE_SUCCESS = 'ADMIN_DESTROY_ROLE_SUCCESS';
export const ADMIN_DESTROY_ROLE_FAIL = 'ADMIN_DESTROY_ROLE_FAIL';